// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "lgubaseopenapi.h"

/////////////////////////////////////////////////////////////////////////////
// CLGUBaseOpenApi

IMPLEMENT_DYNCREATE(CLGUBaseOpenApi, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CLGUBaseOpenApi properties

/////////////////////////////////////////////////////////////////////////////
// CLGUBaseOpenApi operations

BOOL CLGUBaseOpenApi::ConnectServer(LPCTSTR strAddress, LPCTSTR strPort, LPCTSTR strUserID, LPCTSTR strUserPwd)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strAddress, strPort, strUserID, strUserPwd);
	return result;
}

void CLGUBaseOpenApi::GetQStatus(LPCTSTR strType, LPCTSTR strQueue, LPCTSTR strPeer)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strType, strQueue, strPeer);
}

BOOL CLGUBaseOpenApi::IsConnected()
{
	BOOL result;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CLGUBaseOpenApi::DisconnectServer()
{
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CLGUBaseOpenApi::Click2Call(LPCTSTR strPhoneNum, LPCTSTR strCID, LPCTSTR strContext)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strPhoneNum, strCID, strContext);
}

void CLGUBaseOpenApi::SetLogMode(short bSave)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bSave);
}

void CLGUBaseOpenApi::SetEncryption(short bUse)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bUse);
}

void CLGUBaseOpenApi::SendSIPCommand(LPCTSTR strCommand)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strCommand);
}

BOOL CLGUBaseOpenApi::LoginBySWP(LPCTSTR strId, LPCTSTR strPasswd, LPCTSTR strServer)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strId, strPasswd, strServer);
	return result;
}

void CLGUBaseOpenApi::SetOamServerIP(LPCTSTR strOamUrl)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strOamUrl);
}

void CLGUBaseOpenApi::HangUp()
{
	InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CLGUBaseOpenApi::Answer()
{
	InvokeHelper(0xc, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CLGUBaseOpenApi::Transfer(LPCTSTR strExten)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strExten);
}

void CLGUBaseOpenApi::AtXfer(LPCTSTR strExten)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strExten);
}

void CLGUBaseOpenApi::AtXferCID(LPCTSTR strExten, LPCTSTR strCID)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strExten, strCID);
}

BOOL CLGUBaseOpenApi::LoginServer(LPCTSTR strId, LPCTSTR strPasswd, LPCTSTR strServer)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strId, strPasswd, strServer);
	return result;
}

void CLGUBaseOpenApi::SetSeedEncryption()
{
	InvokeHelper(0x11, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CLGUBaseOpenApi::RemoteCall(LPCTSTR Caller1, LPCTSTR CallerId, LPCTSTR Caller2, LPCTSTR Context)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Caller1, CallerId, Caller2, Context);
}

void CLGUBaseOpenApi::GetSettingInfo(LPCTSTR strType)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strType);
}

void CLGUBaseOpenApi::SetAgentStatus(LPCTSTR AgentID, LPCTSTR AgentStatus)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 AgentID, AgentStatus);
}

void CLGUBaseOpenApi::QueueLogin(LPCTSTR strExten, LPCTSTR strQueue)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strExten, strQueue);
}

void CLGUBaseOpenApi::QueueLogout(LPCTSTR strExten, LPCTSTR strQueue)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strExten, strQueue);
}

void CLGUBaseOpenApi::QueueStatus(LPCTSTR strExten, LPCTSTR strQueue, LPCTSTR strPaused, LPCTSTR strState)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strExten, strQueue, strPaused, strState);
}

void CLGUBaseOpenApi::HangUpDst()
{
	InvokeHelper(0x18, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CLGUBaseOpenApi::HangUpChannel(LPCTSTR strChannel)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strChannel);
}

void CLGUBaseOpenApi::SetHeartBeat(short nTime)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nTime);
}

void CLGUBaseOpenApi::SpyExten(LPCTSTR strExten, LPCTSTR strMode)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strExten, strMode);
}

void CLGUBaseOpenApi::SetForward(LPCTSTR strUse, LPCTSTR strForwardType, LPCTSTR strForwardCall, LPCTSTR forwardTimeStart, LPCTSTR forwardTimeEnd, LPCTSTR forwardEtc)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strUse, strForwardType, strForwardCall, forwardTimeStart, forwardTimeEnd, forwardEtc);
}

void CLGUBaseOpenApi::StartRecord()
{
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CLGUBaseOpenApi::StopRecord()
{
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CLGUBaseOpenApi::SendSMS(LPCTSTR strType, LPCTSTR strInfo, LPCTSTR strPeers, LPCTSTR strMsg)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strType, strInfo, strPeers, strMsg);
}

void CLGUBaseOpenApi::SetUserInfo(LPCTSTR strType, LPCTSTR strValue)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strType, strValue);
}

void CLGUBaseOpenApi::GetPeerInfo(LPCTSTR strPeer)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strPeer);
}

void CLGUBaseOpenApi::GetCallHistory(LPCTSTR strSearchCat, LPCTSTR strInOut, LPCTSTR strStart, LPCTSTR strEnd, LPCTSTR strSearch)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strSearchCat, strInOut, strStart, strEnd, strSearch);
}

void CLGUBaseOpenApi::Hold()
{
	InvokeHelper(0x23, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CLGUBaseOpenApi::Unhold()
{
	InvokeHelper(0x24, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CLGUBaseOpenApi::Pickup(LPCTSTR strPickup)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strPickup);
}

void CLGUBaseOpenApi::EncConnectServer(LPCTSTR strAddress, LPCTSTR strPort, LPCTSTR strUserID, LPCTSTR strUserPwd)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strAddress, strPort, strUserID, strUserPwd);
}

void CLGUBaseOpenApi::GetEncStr(LPCTSTR commonstr)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 commonstr);
}

void CLGUBaseOpenApi::SetAutoReconnect(short nTime)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nTime);
}

void CLGUBaseOpenApi::SendPeerMsg(LPCTSTR strType, LPCTSTR strInfo, LPCTSTR strPeers, LPCTSTR strMsg)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strType, strInfo, strPeers, strMsg);
}

void CLGUBaseOpenApi::RedirectConference(LPCTSTR room)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 room);
}

void CLGUBaseOpenApi::InviteConference(LPCTSTR room, LPCTSTR strPeers)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 room, strPeers);
}

void CLGUBaseOpenApi::RemoveConference(LPCTSTR room, LPCTSTR Channels)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 room, Channels);
}

void CLGUBaseOpenApi::JoinConference(LPCTSTR room)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 room);
}

void CLGUBaseOpenApi::GetStatusPeers(LPCTSTR strPeers, LPCTSTR room)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strPeers, room);
}

void CLGUBaseOpenApi::GetBlindDtmf(LPCTSTR strSound, LPCTSTR digitLen)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strSound, digitLen);
}

void CLGUBaseOpenApi::GetRecordList(LPCTSTR strInOut, LPCTSTR strStart, LPCTSTR strEnd, LPCTSTR strSearch)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strInOut, strStart, strEnd, strSearch);
}

void CLGUBaseOpenApi::CallWithConference(LPCTSTR room, LPCTSTR strPeers)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 room, strPeers);
}

void CLGUBaseOpenApi::MagAddrList(LPCTSTR cmd, LPCTSTR keyidx, LPCTSTR grpname, LPCTSTR pname, LPCTSTR telnum1, LPCTSTR telnum2, LPCTSTR telnum3, LPCTSTR telnum4, LPCTSTR telnum5, LPCTSTR defnum, LPCTSTR memo)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 cmd, keyidx, grpname, pname, telnum1, telnum2, telnum3, telnum4, telnum5, defnum, memo);
}

void CLGUBaseOpenApi::SetVarInfo(LPCTSTR varName, LPCTSTR varValue, LPCTSTR strOption)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 varName, varValue, strOption);
}

void CLGUBaseOpenApi::GetVarInfo(LPCTSTR varName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 varName);
}

BOOL CLGUBaseOpenApi::LoginByAdmin(LPCTSTR strId, LPCTSTR strPasswd, LPCTSTR strServer)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strId, strPasswd, strServer);
	return result;
}

void CLGUBaseOpenApi::GetConfMemberList(LPCTSTR strRoom)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x36, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strRoom);
}

void CLGUBaseOpenApi::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
