// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLGUBaseOpenApi wrapper class

class CLGUBaseOpenApi : public CWnd
{
protected:
	DECLARE_DYNCREATE(CLGUBaseOpenApi)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x86019f2f, 0x2899, 0x4c4c, { 0xa6, 0xfe, 0x24, 0xcf, 0xf7, 0xcd, 0x6d, 0x4c } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL ConnectServer(LPCTSTR strAddress, LPCTSTR strPort, LPCTSTR strUserID, LPCTSTR strUserPwd);
	void GetQStatus(LPCTSTR strType, LPCTSTR strQueue, LPCTSTR strPeer);
	BOOL IsConnected();
	void DisconnectServer();
	void Click2Call(LPCTSTR strPhoneNum, LPCTSTR strCID, LPCTSTR strContext);
	void SetLogMode(short bSave);
	void SetEncryption(short bUse);
	void SendSIPCommand(LPCTSTR strCommand);
	BOOL LoginBySWP(LPCTSTR strId, LPCTSTR strPasswd, LPCTSTR strServer);
	void SetOamServerIP(LPCTSTR strOamUrl);
	void HangUp();
	void Answer();
	void Transfer(LPCTSTR strExten);
	void AtXfer(LPCTSTR strExten);
	void AtXferCID(LPCTSTR strExten, LPCTSTR strCID);
	BOOL LoginServer(LPCTSTR strId, LPCTSTR strPasswd, LPCTSTR strServer);
	void SetSeedEncryption();
	void RemoteCall(LPCTSTR Caller1, LPCTSTR CallerId, LPCTSTR Caller2, LPCTSTR Context);
	void GetSettingInfo(LPCTSTR strType);
	void SetAgentStatus(LPCTSTR AgentID, LPCTSTR AgentStatus);
	void QueueLogin(LPCTSTR strExten, LPCTSTR strQueue);
	void QueueLogout(LPCTSTR strExten, LPCTSTR strQueue);
	void QueueStatus(LPCTSTR strExten, LPCTSTR strQueue, LPCTSTR strPaused, LPCTSTR strState);
	void HangUpDst();
	void HangUpChannel(LPCTSTR strChannel);
	void SetHeartBeat(short nTime);
	void SpyExten(LPCTSTR strExten, LPCTSTR strMode);
	void SetForward(LPCTSTR strUse, LPCTSTR strForwardType, LPCTSTR strForwardCall, LPCTSTR forwardTimeStart, LPCTSTR forwardTimeEnd, LPCTSTR forwardEtc);
	void StartRecord();
	void StopRecord();
	void SendSMS(LPCTSTR strType, LPCTSTR strInfo, LPCTSTR strPeers, LPCTSTR strMsg);
	void SetUserInfo(LPCTSTR strType, LPCTSTR strValue);
	void GetPeerInfo(LPCTSTR strPeer);
	void GetCallHistory(LPCTSTR strSearchCat, LPCTSTR strInOut, LPCTSTR strStart, LPCTSTR strEnd, LPCTSTR strSearch);
	void Hold();
	void Unhold();
	void Pickup(LPCTSTR strPickup);
	void EncConnectServer(LPCTSTR strAddress, LPCTSTR strPort, LPCTSTR strUserID, LPCTSTR strUserPwd);
	void GetEncStr(LPCTSTR commonstr);
	void SetAutoReconnect(short nTime);
	void SendPeerMsg(LPCTSTR strType, LPCTSTR strInfo, LPCTSTR strPeers, LPCTSTR strMsg);
	void RedirectConference(LPCTSTR room);
	void InviteConference(LPCTSTR room, LPCTSTR strPeers);
	void RemoveConference(LPCTSTR room, LPCTSTR Channels);
	void JoinConference(LPCTSTR room);
	void GetStatusPeers(LPCTSTR strPeers, LPCTSTR room);
	void GetBlindDtmf(LPCTSTR strSound, LPCTSTR digitLen);
	void GetRecordList(LPCTSTR strInOut, LPCTSTR strStart, LPCTSTR strEnd, LPCTSTR strSearch);
	void CallWithConference(LPCTSTR room, LPCTSTR strPeers);
	void MagAddrList(LPCTSTR cmd, LPCTSTR keyidx, LPCTSTR grpname, LPCTSTR pname, LPCTSTR telnum1, LPCTSTR telnum2, LPCTSTR telnum3, LPCTSTR telnum4, LPCTSTR telnum5, LPCTSTR defnum, LPCTSTR memo);
	void SetVarInfo(LPCTSTR varName, LPCTSTR varValue, LPCTSTR strOption);
	void GetVarInfo(LPCTSTR varName);
	BOOL LoginByAdmin(LPCTSTR strId, LPCTSTR strPasswd, LPCTSTR strServer);
	void GetConfMemberList(LPCTSTR strRoom);
	void AboutBox();
};
